export const CONTACT_REQUEST = "CONTACT_REQUEST";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAILURE = "CONTACT_FAILURE";

export const INTUIT_LOGIN_REQUEST = "INTUIT_LOGIN_REQUEST";
export const INTUIT_LOGIN_SUCCESS = "INTUIT_LOGIN_SUCCESS";
export const INTUIT_LOGIN_FAILURE = "INTUIT_LOGIN_FAILURE";
export const INTUIT_GETAPP_REQUEST = "INTUIT_GETAPP_REQUEST";
export const INTUIT_GETAPP_SUCCESS = "INTUIT_GETAPP_SUCCESS";
export const INTUIT_GETAPP_FAILURE = "INTUIT_GETAPP_FAILURE";
export const INTUIT_CALLBACK_REQUEST = "INTUIT_CALLBACK_REQUEST";
export const INTUIT_CALLBACK_SUCCESS = "INTUIT_CALLBACK_SUCCESS";
export const INTUIT_CALLBACK_FAILURE = "INTUIT_CALLBACK_FAILURE";
export const INTUIT_LOGOUT = "INTUIT_LOGOUT";
