export const INTUIT_LOGIN_REQUEST = 'INTUIT_LOGIN_REQUEST';
export const INTUIT_LOGIN_SUCCESS = 'INTUIT_LOGIN_SUCCESS';
export const INTUIT_LOGIN_FAILURE = 'INTUIT_LOGIN_FAILURE';
export const INTUIT_GETAPP_REQUEST = 'INTUIT_GETAPP_REQUEST';
export const INTUIT_GETAPP_SUCCESS = 'INTUIT_GETAPP_SUCCESS';
export const INTUIT_GETAPP_FAILURE = 'INTUIT_GETAPP_FAILURE';
export const INTUIT_CALLBACK_REQUEST = 'INTUIT_CALLBACK_REQUEST';
export const INTUIT_CALLBACK_FAILURE = 'INTUIT_CALLBACK_FAILURE';

export const RECEIVE_LOGIN_TOKEN = 'RECEIVE_LOGIN_TOKEN';
export const INTUIT_LOGOUT = 'INTUIT_LOGOUT';
export const SWITCH_COMPANY = 'SWITCH_COMPANY';

export const INTUIT_DISCONNECT_REQUEST = 'INTUIT_DISCONNECT_REQUEST';
export const INTUIT_DISCONNECT_SUCCESS = 'INTUIT_DISCONNECT_SUCCESS';
export const INTUIT_DISCONNECT_FAILURE = 'INTUIT_DISCONNECT_FAILURE';

export const REFRESH_USER_INFO_REQUEST = 'REFRESH_USER_INFO_REQUEST';
export const REFRESH_USER_INFO_SUCCESS = 'REFRESH_USER_INFO_SUCCESS';
export const REFRESH_USER_INFO_FAILURE = 'REFRESH_USER_INFO_FAILURE';

export const GET_COMPANY_INFO_REQUEST = 'GET_COMPANY_INFO_REQUEST';
export const GET_COMPANY_INFO_SUCCESS = 'GET_COMPANY_INFO_SUCCESS';
export const GET_COMPANY_INFO_FAILURE = 'GET_COMPANY_INFO_FAILURE';

export const UPLOAD_INVOICES_REQUEST = 'UPLOAD_INVOICES_REQUEST';
export const UPLOAD_INVOICES_SUCCESS = 'UPLOAD_INVOICES_SUCCESS';
export const UPLOAD_INVOICES_FAILURE = 'UPLOAD_INVOICES_FAILURE';

export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAILURE = 'SEND_CONTACT_FAILURE';
